//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLinqTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TDMS_FILE_INFO> TDMS_FILE_INFO { get; set; }
        public DbSet<TDMS_MATERIAL_INFO> TDMS_MATERIAL_INFO { get; set; }
        public DbSet<TDMS_PREDEFINED_DATA> TDMS_PREDEFINED_DATA { get; set; }
        public DbSet<TDMS_PROCEDURE_CATE> TDMS_PROCEDURE_CATE { get; set; }
        public DbSet<TDMS_PROCEDURE_INFO> TDMS_PROCEDURE_INFO { get; set; }
        public DbSet<TDMS_PROJECT_INFO> TDMS_PROJECT_INFO { get; set; }
    }
}
