//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLinqTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDMS_PROJECT_INFO
    {
        public long PRO_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PMO { get; set; }
        public string SPONSOR { get; set; }
        public string TECHNOLOGY { get; set; }
        public string CUSTOMER { get; set; }
        public string APPLICATION { get; set; }
        public string KEY_WORDS { get; set; }
        public string FILE_PATH { get; set; }
        public string M0_STATUS { get; set; }
        public Nullable<System.DateTime> M0_TIME { get; set; }
        public string T0_STATUS { get; set; }
        public Nullable<System.DateTime> T1_TIME { get; set; }
        public string T2_STATUS { get; set; }
        public Nullable<System.DateTime> T2_TIME { get; set; }
        public string IS_DELETE { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<System.DateTime> T0_TIME { get; set; }
        public string T1_STATUS { get; set; }
    }
}
