//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLinqTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDMS_FILE_INFO
    {
        public long FILE_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<long> CATE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string IS_DELETE { get; set; }
    }
}
