//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLinqTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDMS_MATERIAL_INFO
    {
        public decimal MATERIAL_ID { get; set; }
        public string CATEGORY { get; set; }
        public string MATERIAL { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public Nullable<decimal> CATE_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
    }
}
